# This is a Jupyter Notebook that explains Numpy Random Package

### NumPy is an extention to python which adds multidementional array sipport to python. 

###### NumPy helps in Data Analysis   

In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5,6,10.5]
b=np.array(a)
print(b)


[ 1.   2.   3.   4.   5.   6.  10.5]


In [3]:
print(b*3)

[ 3.   6.   9.  12.  15.  18.  31.5]


In [4]:
c=np.arange(1,10)

In [5]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arange when passed two number gives back an array from the first number up to and not including the second number

arange when passed three parameters it is the same as two but the third parameter shows the distance between the numbers

In [6]:
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [7]:
e = np.array([[1,2,3],[4,5,6]])

In [8]:
e


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
e.ndim

2

ndim = number of dimentions in that array

In [10]:
b.ndim

1

In [11]:
np.shape(e)

(2, 3)

np.shape(e) means the number or arrays and number of elements per array in the array e

In [12]:
print (e[0])

[1 2 3]


print (e[0]) prints out the first array in e

In [13]:
print (e[0][1])

2


print (e[0][1]) prints  out the second element in the first array

In [14]:
f = np.random.randn(3,5)

In [15]:
f

array([[ 0.63255598, -1.43848947,  0.82436793,  0.0150219 ,  0.31703401],
       [-2.14737665,  0.67498187, -0.02074346,  1.60224799, -1.05524157],
       [-0.4747467 ,  1.11627168, -0.64301584, -0.62225983,  0.09235635]])

np.random.randn(3,5) prints out a random multidimentional array with array size 3 and 5 elements per array