# This is a Jupyter Notebook that explains Numpy Random Package

### NumPy is an extention to python which adds multidementional array sipport to python. 

###### NumPy helps in Data Analysis   

In [4]:
import numpy as np

In [10]:
a=[1,2,3,4,5,6,10.5]
b=np.array(a)
print(b)


[ 1.   2.   3.   4.   5.   6.  10.5]


In [11]:
print(b*3)

[ 3.   6.   9.  12.  15.  18.  31.5]


In [15]:
c=np.arange(1,10)

In [16]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arange when passed two number gives back an array from the first number up to and not including the second number

arange when passed three parameters it is the same as two but the third parameter shows the distance between the numbers

In [18]:
d=np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])